### ISSUE TITLE
Revise.jl is in Project.toml but not used

### ISSUE THREAD

**Issue by singularitti** [glwhart/Spacey.jl#3]
Great package! Thank you for making it!
I found that [`Revise.jl`](https://github.com/timholy/Revise.jl) is included as a [dependency in this project](https://github.com/glwhart/Spacey.jl/blob/1f330fce427a080a9a726be67aca9cc74476fc62/Project.toml#L9).
However, after a cursory view, I do not think `Revise.jl` is imported anywhere in this code. I guess you are using it for development.
But this is not necessary. According to [Julia's code loading order](https://docs.julialang.org/en/v1/base/constants/#Base.LOAD_PATH), it loads the local environment (a directory with a `Project.toml` file) first, then the global environment (usually `~/.julia` on a *nix OS). So you could just delete that line and install `Revise.jl` in a global environment and put the following lines in `~/.julia/config/startup.jl`:

```julia
try
    @eval using Revise
catch e
    @warn "Error initializing Revise" exception=(e, catch_backtrace())
end
```
as instructed by [`Reivse.jl`'s documentation](https://timholy.github.io/Revise.jl/stable/config/#Using-Revise-automatically-within-Jupyter/IJulia-1).

**Comment by glwhart** [comment]
Thanks for the help. I fixed this.
